name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Wheels
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pybind11

      # Build the wheel
      - name: Build Wheel
        run: python setup.py bdist_wheel

      # Upload built wheels as artifacts
      - name: Upload Built Wheels
        uses: actions/upload-artifact@v3
        with:
          name: binaryparser-wheels
          path: dist/*.whl

      # Install the built wheel
      - name: Install Built Package
        run: |
          pip install dist/*.whl


      # Test the package (optional)
      - name: Run Tests
        run: |
          python ./tests/test.py
